version: "3.8"

services:
  laravel:
    container_name: laravel
    build: 
      context: ./laravelWebsite
      dockerfile: ./dockerfile
    image: localhost/laravel:latest
    ports:
      - "8000:8000" # php artisan serve
      - "5173:5173" # npm run dev
    volumes:
      - ./laravelWebsite/:/app:Z # For Development
    networks:
      - app-network
    depends_on:
      - dotnet

  dotnet:
    container_name: soap_dotnet
    build:
      context: ./SoapDotnet
      dockerfile: ./dockerfile
    image: localhost/dotnet:latest
    ports:
      - "8001:5109"
    volumes:
      - ./SoapDotnet:/app:Z # For Development
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
      container_name: postgres
      build:
        context: ./postgresDatabase
        dockerfile: ./dockerfile
      image: localhost/postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_MULTIPLE_DB: user_profile_database,laravel_user_database
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data # Persistent Data Storage
      networks:
      - app-network

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

volumes:
    postgres_data:

networks:
    app-network:
      driver: bridge
