version: "3.8"

services:
  laravel:
    container_name: laravel
    build: 
      context: ./laravelWebsite
      dockerfile: ./dockerfile
    image: localhost/laravelwebsite:latest
    ports:
      - "8000:8000" # php artisan serve
      - "5173:5173" # npm run dev
    volumes:
      - ./laravelWebsite/:/app:Z # For Development
    networks:
      - app-network
    depends_on:
      - dotnet
      - graphql
      - mqttsensors

  dotnet:
    container_name: soap_dotnet
    build:
      context: ./SoapDotnet
      dockerfile: ./dockerfile
    image: localhost/soapdotnet:latest
    ports:
      - "8001:5109"
    volumes:
      - ./SoapDotnet:/app:Z # For Development
    networks:
      - app-network
    depends_on:
      - postgres

  graphql:
    container_name: graphql_go
    build:
      context: ./GraphqlAgenda
      dockerfile: ./dockerfile
    image: localhost/graphqlgo:latest
    ports:
      - "8002:8060"
    networks:
      - app-network
    depends_on:
      - postgres

  mqttsensors:
    container_name: mqtt_sensors
    build:
      context: ./MqttSensors
      dockerfile: ./dockerfile
    image: localhost/mqttsensors:latest
    networks:
      - app-network
    depends_on:
      - mqttbroker
  
  mqttbroker:
    container_name: mqtt_broker
    image: docker.io/eclipse-mosquitto:latest
    volumes:
      - "./MqttBroker/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:Z"
      - "./MqttBroker/data:/mosquitto/data:Z"
      - "./MqttBroker/log:/mosquitto/log:Z"
    ports:
      - "8003:1883"
    networks:
      - app-network

  postgres:
      container_name: postgres
      build:
        context: ./postgresDatabase
        dockerfile: ./dockerfile
      image: localhost/postgresdb:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_MULTIPLE_DB: user_profile_database,laravel_user_database,graphql_agenda_database
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data # Persistent Data Storage
      networks:
      - app-network

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
    postgres_data:

networks:
    app-network:
      driver: bridge
