package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	dbModels "agenda/Models"
	"agenda/graph/model"
	"context"
	"fmt"
)

// CreateAgendaEvent is the resolver for the createAgendaEvent field.
func (r *mutationResolver) CreateAgendaEvent(ctx context.Context, userID int, doctorID int, title string, description *string, date model.DateInputRequired, timeBegin model.TimeInputRequired, timeEnd model.TimeInputRequired) (*model.AgendaEvent, error) {
	agendaEvent := &dbModels.AgendaEvent{
		UserID:      uint(userID),
		DoctorID:    uint(doctorID),
		Title:       title,
		Description: *description,
		Year:        uint(date.Year),
		Month:       uint(date.Month),
		Day:         uint(date.Day),
		HourBegin:   uint(timeBegin.Hour),
		MinuteBegin: uint(timeBegin.Minute),
		HourEnd:     uint(timeEnd.Hour),
		MinuteEnd:   uint(timeEnd.Minute),
	}

	if err := r.DB.Create(agendaEvent).Error; err != nil {
		return nil, fmt.Errorf("failed to create AgendaEvent: %v", err)
	}

	agendaEventModel := dbModels.GormToGraphqlModel(agendaEvent)
	return &agendaEventModel, nil
}

// UpdateAgendaEvent is the resolver for the updateAgendaEvent field.
func (r *mutationResolver) UpdateAgendaEvent(ctx context.Context, id int, title *string, description *string, date *model.DateInput, timeBegin *model.TimeInput, timeEnd *model.TimeInput) (*model.AgendaEvent, error) {
	var agendaEvent dbModels.AgendaEvent
	if err := r.DB.First(&agendaEvent, id).Error; err != nil {
		return nil, fmt.Errorf("invalid event: ID not found")
	}
	updates := map[string]interface{}{}
	if title != nil {
		updates["title"] = *title
	}
	if description != nil {
		updates["description"] = *description
	}
	if date != nil {
		if date.Year != nil {
			updates["year"] = *date.Year
		}
		if date.Month != nil {
			updates["month"] = *date.Month
		}
		if date.Day != nil {
			updates["day"] = *date.Day
		}
	}
	if timeBegin != nil {
		if timeBegin.Hour != nil {
			updates["hour"] = *timeBegin.Hour
		}
		if timeBegin.Minute != nil {
			updates["minute"] = *timeBegin.Minute
		}
	}
	if timeEnd != nil {
		if timeEnd.Hour != nil {
			updates["hour"] = *timeEnd.Hour
		}
		if timeEnd.Minute != nil {
			updates["minute"] = *timeEnd.Minute
		}
	}

	if err := r.DB.Model(&agendaEvent).Updates(updates).Error; err != nil {
		return nil, fmt.Errorf("failed to update: %v", err)
	}

	agendaEventModel := dbModels.GormToGraphqlModel(&agendaEvent)
	return &agendaEventModel, nil
}

// DeleteAgendaEvent is the resolver for the deleteAgendaEvent field.
func (r *mutationResolver) DeleteAgendaEvent(ctx context.Context, id string) (bool, error) {
	var agendaEvent dbModels.AgendaEvent
	if err := r.DB.First(&agendaEvent, id).Error; err != nil {
		return false, fmt.Errorf("invalid event: ID not found")
	}

	if err := r.DB.Delete(&agendaEvent).Error; err != nil {
		return false, fmt.Errorf("failed to delete: %v", err)
	}

	return true, nil
}

// GetAgenda is the resolver for the getAgenda field.
func (r *queryResolver) GetAgenda(ctx context.Context, id string) (*model.AgendaEvent, error) {
	var agendaEvent dbModels.AgendaEvent
	if err := r.DB.First(&agendaEvent, id).Error; err != nil {
		return nil, fmt.Errorf("invalid event: ID not found")
	}

	agendaEventModel := dbModels.GormToGraphqlModel(&agendaEvent)
	return &agendaEventModel, nil
}

// ListAgendas is the resolver for the listAgendas field.
func (r *queryResolver) ListAgendas(ctx context.Context, userID int) ([]*model.AgendaEvent, error) {
	var agendaEvents []dbModels.AgendaEvent
	if err := r.DB.Where("user_id = ?", userID).Find(&agendaEvents).Error; err != nil {
		return nil, fmt.Errorf("failed to find events: %v", err)
	}

	var result []*model.AgendaEvent
	for _, event := range agendaEvents {
		eventModel := dbModels.GormToGraphqlModel(&event)
		result = append(result, &eventModel)
	}
	return result, nil
}

// GetAgendaEvents is the resolver for the getAgendaEvents field.
func (r *queryResolver) GetAgendaEvents(ctx context.Context, userID int, fromDate model.DateInput, toDate model.DateInput) ([]*model.AgendaEvent, error) {
	var agendaEvents []dbModels.AgendaEvent

	// Filter events within the date bounds
	if err := r.DB.Where("date >= ? AND date <= ?", fromDate, toDate).Find(&agendaEvents).Error; err != nil {
		return nil, fmt.Errorf("failed to find events: %v", err)
	}

	var result []*model.AgendaEvent
	for _, event := range agendaEvents {
		eventModel := dbModels.GormToGraphqlModel(&event)
		result = append(result, &eventModel)
	}
	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
