// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AgendaEvent struct {
	ID          string  `json:"id"`
	UserID      string  `json:"userId"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Year        int     `json:"year"`
	Month       int     `json:"month"`
	Day         int     `json:"day"`
	Hour        int     `json:"hour"`
	Minute      int     `json:"minute"`
}

type Mutation struct {
}

type Query struct {
}
