// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AgendaEvent struct {
	ID          string  `json:"id"`
	UserID      int     `json:"userId"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Year        int     `json:"year"`
	Month       int     `json:"month"`
	Day         int     `json:"day"`
	Hour        *int    `json:"hour,omitempty"`
	Minute      *int    `json:"minute,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
