# docker/laravel-Dockerfile
FROM docker.io/php:8.3-cli

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip \
    curl

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set working directory
WORKDIR /app

# Install Laravel dependencies
COPY . /app
RUN composer install --no-interaction --optimize-autoloader

# # Expose port 8000 and start Laravel
EXPOSE 8000
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
