<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: medicalData.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>InvoicesListResponse</code>
 */
class InvoicesListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .InvoiceResponse invoices = 1;</code>
     */
    private $invoices;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\InvoiceResponse>|\Google\Protobuf\Internal\RepeatedField $invoices
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MedicalData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .InvoiceResponse invoices = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInvoices()
    {
        return $this->invoices;
    }

    /**
     * Generated from protobuf field <code>repeated .InvoiceResponse invoices = 1;</code>
     * @param array<\InvoiceResponse>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInvoices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \InvoiceResponse::class);
        $this->invoices = $arr;

        return $this;
    }

}

